name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Get code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Create env file
      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # 3. Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 4. Build and Push Image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/agriculture_api:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/agriculture_api:latest
